### ISSUE TITLE
YAML issues adding new RTL language

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2162]
Hey!

So as a pet project of mine, I spent time translating Coral for a new language - Hebrew.

I've finally got all the translations in there - as you can see on a branch here: https://github.com/coralproject/talk/compare/master...mkonikov:hebrew

I'm now encountering issues when trying to build with `yarn build` such as this one:

```
Module build failed: YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 432, column 16:
        reject_rate: "שיעור דחייה"
```

Nothing seems off about this YML line so not quite sure what to do next.

Would love to contribute this back - so any suggestions would be great.

**Comment by kgardnr** [comment]
Hey @mkonikov! Wow, thank you so much for this - we're so excited to add Hebrew!!

We will look into this error for you!

**Comment by wyattjoh** [comment]
Found the issue @mkonikov!

Take a look here:

https://github.com/coralproject/talk/compare/master...mkonikov:hebrew#diff-bbce3306fd2cbce22b2debd9e239ec6eR431

You need to escape that `"` inside the translation, and that should fix it!

**Comment by mkonikov** [comment]
Sorry @wyattjoh the link doesn't seem to be working for me: 
![image](https://user-images.githubusercontent.com/7562285/51701686-f465ef80-1fdf-11e9-9a73-ab0ed81c0ee8.png)

**Comment by wyattjoh** [comment]
Try this one:

https://github.com/mkonikov/talk/blob/fa42c028dfba924679ae3ebb15599c938462824a/plugins/talk-plugin-profile-data/client/translations.yml#L157

Essentially, double check that any `"` inside a string is properly escaped with a `\`.

**Comment by mkonikov** [comment]
@wyattjoh I believe I removed all the `"` and still no luck.
Also - are unescaped `"` and issue when enclosed within strings marked with `'`?

**Comment by wyattjoh** [comment]
@mkonikov I was able to clone your repo (https://github.com/mkonikov/talk) and it built successfully, what error are you getting?

**Comment by mkonikov** [comment]
Actually does seem to all be in working order now. Will open PR now.

Thanks @wyattjoh!
